Include 2014 fluxes for IC (solmax) and SK (solmin and solmax) for integral preserving fluxes
icecube/nuflux pull request #12
Opened 2021-07-09 13:23 UTC by pabloferm

Enable below GeV computation for SK fluxes.

2021-07-09 15:11 UTC, kjmeagher requested changes

2021-07-09 15:11 UTC, kjmeagher commented on src/library/IPLEFlux.cpp
> +    if (SetSubGeV==true) return 1e-1;
Please use curly braces here

2021-07-09 15:12 UTC, kjmeagher commented on src/library/IPLEFlux.cpp
> +//    SetSubGeV = fluxName.find("sno") != std::string::npos; // Extend to SubGeV for fluxes at SNO
Don't add dead code

2021-07-11 19:25 UTC, pabloferm commented on src/library/IPLEFlux.cpp
> +    if (SetSubGeV==true) return 1e-1;
Done

2021-07-11 19:25 UTC, pabloferm commented on src/library/IPLEFlux.cpp
> +//    SetSubGeV = fluxName.find("sno") != std::string::npos; // Extend to SubGeV for fluxes at SNO
Removed

2021-07-12 14:35 UTC, merged